config/routes.rb
Rails.application.routes.draw do
  #resources :lectures, only: [:index]
  devise_for :users, path_names: { sign_up: 'register', sign_in: 'login', sign_out: 'log_out' }
  resources :education_programs

  authenticated :user do
    root 'courses#index', as: :authenticated_root
  end

  root to: 'pages#home'

  resources :courses, path: '', except: [:show] do
    put :sort, on: :collection
    resources :notes, shallow: true
    resources :lectures, only: [:index, :show]
  end
  
  get 'notes', to: 'notes#my_notes', as: 'my_notes'
  get 'not_commentable', to: 'notes#not_commentable'

  get 'about', to: 'pages#about'
  get 'contact', to: 'pages#contact'
  mount ActionCable.server => '/cable'
  get ':id', to: 'courses#show', as: 'course_show'
  

  
 # get ':course/:lecture/notes', to: 'lecture#show', as: 'lecture_notes'
  #get ':course/notes', to: 'notes#index', as: 'course_notes'

  
  
  
  
  
  # resources :notes, except: :index do
  #   member do
  #     get :toggle_status
  #   end
  # end
  #get 'notes', to: 'notes#index', as: 'notes_in_course'
  
  
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  
  

 
end

app/models/note.rb
class Note < ApplicationRecord
    enum status: { canComment: 0, cannotComment: 1, privateNote: 2}
    extend FriendlyId
    friendly_id :title, use: :slugged

    validates_presence_of :title, :body, :user_id, :course_id, :lecture_id

    belongs_to :course
    belongs_to :user
    belongs_to :lecture

    has_many :comments, dependent: :destroy

    def self.not_commentable
        where(status: 'cannotComment')
    end

    def self.featured_notes
        limit(2)
    end

    def self.paginate_notes(page)
        page(page).per(10).order('updated_at DESC')
    end

end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_action :set_note, only: [:show, :edit, :update, :destroy, :toggle_status]
  #include SetCurrentCourse
  layout "notes"

  access student: :all, instructor: :all

  # GET /notes
  # GET /notes.json
  def index
    @page_title = "NoteShare | Notes"
    # if check_course
      @course = Course.friendly.find(params[:course_id])
      @notes = Note.where(course_id: @course.id).paginate_notes(params[:page])
      @lectures = Lecture.where(course_id: @course)
    # else
    #   redirect_to my_notes_path
    # end
  end

  def my_notes
    @notes = Note.where(user_id: current_user.id).paginate_notes(params[:page])
  end

  def not_commentable
    @not_commentable_notes = Note.not_commentable
  end

  # GET /notes/1
  # GET /notes/1.json
  def show
    @note = Note.includes(:comments).friendly.find(params[:id])
    @comment = Comment.new

    @page_title = @note.title
    @seo_keywords = @note.body
  end

  # GET /notes/new
  def new
    if check_course
      @note = Note.new
      @course = Course.find_by(slug: params[:course_id])
      #@course_id = Course.find_by(slug: params[:course_id]).id
    else
      redirect_to courses_path, notice: 'Please select a course for your note.'
    end
  end

  # GET /notes/1/edit
  def edit
    @course = @note.course
  end

  # POST /notes
  # POST /notes.json
  def create
    @note = Note.new(note_params)

    respond_to do |format|
      if @note.save
        format.html { redirect_to course_notes_path(params[:course_id]), notice: 'Note was successfully created.' }
        format.json { render :show, status: :created, location: @note }
      else
        format.html { render :new }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /notes/1
  # PATCH/PUT /notes/1.json
  def update
    respond_to do |format|
      if @note.update(note_params)
        format.html { redirect_to my_notes_path, notice: 'Note was successfully updated.' }
        format.json { render :show, status: :ok, location: @note }
      else
        format.html { render :edit }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /notes/1
  # DELETE /notes/1.json
  def destroy
    @note.destroy
    respond_to do |format|
      format.html { redirect_to course_notes_url(@note.course.slug), notice: 'Note was successfully deleted.' }
      format.json { head :no_content }
    end
  end

  def toggle_status
    if @note.cannotComment? || @note.privateNote?
      @note.canComment!
    elsif @note.canComment?
      @note.cannotComment!
    end
    redirect_to course_notes_url(@note.course.slug), notice: 'Note status has been changed to: ' + @note.status
  end

  private

    def check_course
      params[:course_id].present?
      #Note.where(user_id: current_user.id)
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_note
      @note = Note.friendly.find(params[:id])

    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def note_params
      params.require(:note).permit(:title, :body, :course_id, :user_id, :lecture_id)
    end


end

app/helpers/notes_helper.rb
module NotesHelper

    def gravatar_helper (user)
        image_tag "https://www.gravatar.com/avatar/#{Digest::MD5.hexdigest(user.email)}", width: 50, class: 'avatar'
    end

    def show_main_title
        if @lecture
            @lecture.title.titleize
        elsif params[:course_id]
            (params[:course_id]).titleize 
        else
            "My Notes"
        end
    end

    def filter_lectures(note)
        course_id = 0;
        
        if params[:course_id]
            course_id = Course.friendly.find(params[:course_id]).id
        else
            course_id = note.course_id    
        end
        Lecture.where(course_id: course_id) 
    end

    class CodeRayify < Redcarpet::Render::HTML
        def block_code(code, language)
            CodeRay.scan(code, language || :text).div
        end
    end

    def markdown(text)
        coderayified = CodeRayify.new(filter_html: true, hard_wrap: true)

        options = {
            fenced_code_blocks: true,
            no_intra_emphasis: true,
            autolink: true,
            lax_html_blocks: true,
        }

        markdown_to_html = Redcarpet::Markdown.new(coderayified, options)
        markdown_to_html.render(text).html_safe
    end
end

app/views/notes/_form.html.erb
<%= form_with(model: note, url: (@note.new_record? ? [@course, @note] : @note), local: true) do |form| %>
  <% if note.errors.any? %>
    <% note.errors.full_messages.each do |error| %>
      <%= alert_generator(error) %>
    <% end %>
  <% end %>

  <div class="form-group">
    <%= form.label :title %>
    <%= form.text_field :title, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :lecture_id %>
    <%= form.collection_select(:lecture_id, filter_lectures(note), :id, :title, {selected: note.lecture_id, include_blank: true}, {class: "form-control"}) %>
  </div>

  <div class="form-group">
    <%= form.label :body %>
    <%= form.text_area :body, rows: 20, class: "form-control" %>
  </div>
  <div class="form-group">
  
    <%= form.hidden_field :user_id, value: current_user.id, class: "form-control" %>
    <%= form.hidden_field :course_id, value: @course.id, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.submit "Post Note", class: "btn btn-primary btn-block" %>
  </div>
<% end %>

app/views/notes/_note.html.erb
<div class="blog-post">
    <h2 class="blog-post-title"><%= link_to note.title, note %></h2>
    <p class="blog-post-meta">Posted <%= distance_of_time_in_words(note.created_at, Time.now) %> ago, by <%= note.user.name %> </p>
    <p class="blog-post-meta">
        <% (note.user_id == current_user.id) %>
            <%= link_to 'Edit | ', edit_note_path(note) %>
            <%= link_to 'Remove Note', note, method: :delete, data: { confirm: 'Are you sure?' } %>
        <% end %>
    </p>

    <p><%= markdown(note.body.truncate(35)) %></p>
    <hr>
</div>

app/views/notes/edit.html.erb
<div class="col-md-8 blog-main">
    <h1>Editing Note</h1>

    <%= render 'form', note: @note %>

    <%= link_to 'Back', course_notes_path(@note.course) %>
</div>

app/views/notes/index.html.erb
<%= render 'shared/notes_main_content' %>

app/views/notes/my_notes.html.erb
<%= render 'shared/notes_main_content' %>

app/views/notes/new.html.erb
<div class="col-md-8 blog-main">
    <h1>New Note</h1>

    <%= render 'form', note: @note %>

    <%= link_to 'Back', course_notes_path(params[:course_id]) %>
</div>

app/views/notes/not_commentable.html.erb
<p id="notice"><%= notice %></p>

<h1>Uncommentable Notes</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th colspan="4"></th>
    </tr>
  </thead>

  <tbody>
    <% @not_commentable_notes.each do |note| %>
      <tr>
        <td><%= note.title %></td>
        <td><%= note.body %></td>
        <td><%= link_to note.status, toggle_status_note_path(note) %></td>
        <td><%= link_to 'Show', note %></td>
        <td><%= link_to 'Edit', edit_note_path(note) %></td>
        <td><%= link_to 'Destroy', note, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Note', new_note_path %>

app/views/notes/show.html.erb
<div class="col-md-8 blog-main">
  <h2 class="pb-3 mb-4 font-italic border-bottom">
    <%= @note.title %>
  </h2>
  <%= link_to 'Edit', edit_note_path(@note) if current_user == @note.user %>
  <p>
    <%= @note.lecture.title %>
  </p>
  <p>
    <%= markdown(@note.body) %>
  </p>

  <%= render 'comments/comment_form' %>
  <div id="comments" data-note-id="<%= @note.id %>">
    <%= render @note.comments %>
  </div>
</div><!-- /.blog-main -->