config/routes.rb
Rails.application.routes.draw do
  #resources :lectures, only: [:index]
  devise_for :users, path_names: { sign_up: 'register', sign_in: 'login', sign_out: 'log_out' }
  resources :education_programs

  authenticated :user do
    root 'courses#index', as: :authenticated_root
  end

  root to: 'pages#home'

  resources :courses, path: '', except: [:show] do
    put :sort, on: :collection
    resources :notes, shallow: true
    resources :lectures, only: [:index, :show]
  end
  
  get 'notes', to: 'notes#my_notes', as: 'my_notes'
  get 'not_commentable', to: 'notes#not_commentable'

  get 'about', to: 'pages#about'
  get 'contact', to: 'pages#contact'
  mount ActionCable.server => '/cable'
  get ':id', to: 'courses#show', as: 'course_show'
  

  
 # get ':course/:lecture/notes', to: 'lecture#show', as: 'lecture_notes'
  #get ':course/notes', to: 'notes#index', as: 'course_notes'

  
  
  
  
  
  # resources :notes, except: :index do
  #   member do
  #     get :toggle_status
  #   end
  # end
  #get 'notes', to: 'notes#index', as: 'notes_in_course'
  
  
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  
  

 
end

app/views/shared/_application_footer.html.erb
<footer class="mastfoot mt-auto">
    <div class="inner">
        <p><%= copyright_generator %></p>
    </div>
</footer>

app/views/shared/_application_navbar.html.erb
<header class="masthead mb-auto">
    <div class="inner">
        <h3 class="masthead-brand">NoteShare</h3>
        <nav class="nav nav-masthead justify-content-center app-navbar">
            <%= navbar_helper("nav-link", "span") %>
            <%= login_helper("nav-link") %>
        </nav>
    </div>
</header>

app/views/shared/_courses_footer.html.erb
<footer class="text-muted">
	<div class="container">
		<p class="float-right">
			<a href="#">Back to top</a>
            <%= link_to 'Show All Courses', courses_path %>
		</p>
		<p>
		<%= copyright_generator %>
		</p>
		<%= source_helper %>
	</div>
</footer>

app/views/shared/_courses_masthead.html.erb
<section class="jumbotron text-center">
	<div class="container">
		<h1 class="jumbotron-heading"><%= current_user.education_program.title %></h1>
		<p class="lead text-muted"><%= current_user.education_program.academic_degree %></p>
	</div>
</section>

app/views/shared/_courses_navbar.html.erb
<header>
	<div class="collapse bg-dark" id="navbarHeader">
		<div class="container">
			<div class="row">
				<div class="col-sm-8 col-md-7 py-4">
					<h4 class="text-white">About</h4>
					<p class="text-muted">Add some information about the album below, the author, or any other background context. Make it a few sentences long so folks can pick up some informative tidbits. Then, link them off to some social networking sites or contact information.</p>
				</div>
				<div class="col-sm-4 offset-md-1 py-4">
					<h4 class="text-white">Menu</h4>
					<ul class="list-unstyled">
						<%= navbar_helper("text-white", "li") %>
						<li><%= login_helper "text-white" %></li>
					</ul>
				</div>
			</div>
		</div>
	</div>
	<div class="navbar navbar-dark bg-dark box-shadow">
		<div class="container d-flex justify-content-between">
			<a href="#" class="navbar-brand d-flex align-items-center">
				<strong>NoteShare</strong>
			</a>
			<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarHeader" aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
				<span class="navbar-toggler-icon"></span>
			</button>
		</div>
	</div>
</header>

 

app/views/shared/_navbar.html.erb
   
    <div class="<%= location %>" >
      <div><%= link_to "Home", root_path %></div>
      <div><%= link_to "About", about_path %></div>
      <div><%= link_to "Contact", contact_path %></div>
      <div><%= link_to "Notes", my_notes_path %></div>
      <div><%= link_to "Courses", courses_path %></div>
      <div><%= link_to "Education Programs", education_programs_path %></div>
    </div>

app/views/shared/_notes_cards.html.erb
<div class="row">
  <div class="col-md-6">
    <%= link_to new_course_note_path(params[:course_id]) do %>
      <div class="card flex-md-row mb-4 box-shadow h-md-200">
        <div class="card-body d-flex flex-column align-items-start">
          <h3 class="mb-0">Post a new note</h3>
          <p class="card-text mb-auto">Add a new note to the collection.</p>
        </div>
      </div>
    <% end %>
  </div>
  <div class="col-md-6">
    <%= link_to course_show_path(params[:course_id]) do %>
      <div class="card flex-md-row mb-4 box-shadow h-md-200">
        <div class="card-body d-flex flex-column align-items-start">
          <h3 class="mb-0"><%= params[:course_id].titleize %></h3>
          <p class="card-text mb-auto">See curriculum.</p>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/shared/_notes_footer.html.erb
    <footer class="blog-footer">
      <%= source_helper %>
      <%= copyright_generator %>
      <p>
        <a href="#">Back to top</a>
      </p>
    </footer>

app/views/shared/_notes_main_content.html.erb
<h3 class=" col-md-12 border-bottom">
  <%= show_main_title %> 
</h3>

<div class="col-md-8">
    <%= render 'shared/notes_cards' if @course %>

   
  <%= paginate @notes %> 

  <%= render @notes %> 

  <%= paginate @notes %> 

</div>


 


<div class="col-md-4">
    <%= render 'shared/notes_sidebar' if @course %>
</div>

app/views/shared/_notes_masthead.html.erb
<div class="container">
    <%= render 'shared/notes_navbar' %>
</div>

app/views/shared/_notes_navbar.html.erb
<header class="blog-header py-3">
    <div class="row flex-nowrap justify-content-between align-items-center">
        <div class="col-12 text-center">
            <%= link_to "NoteShare", root_path, class: "blog-header-logo text-light" %>
        </div>
    </div>
</header>

<div class="nav-scroller py-1 mb-2">
    <nav class="nav d-flex justify-content-between">
        <%= navbar_helper("text-muted", "span") %>
        <%= login_helper("text-muted") %>
  </nav>
</div>

 
  

app/views/shared/_notes_sidebar.html.erb
<aside class="blog-sidebar">
    <h4 class="font-italic">Lectures</h4>
    <div class="list-unstyled mb-0">
      <%= render @lectures, partial: 'lectures/lecture'  %>
    </div>
</aside>