config/routes.rb
Rails.application.routes.draw do
  #resources :lectures, only: [:index]
  devise_for :users, path_names: { sign_up: 'register', sign_in: 'login', sign_out: 'log_out' }
  resources :education_programs

  authenticated :user do
    root 'courses#index', as: :authenticated_root
  end

  root to: 'pages#home'

  resources :courses, path: '', except: [:show] do
    put :sort, on: :collection
    resources :notes, shallow: true
    resources :lectures, only: [:index, :show]
  end
  
  get 'notes', to: 'notes#my_notes', as: 'my_notes'
  get 'not_commentable', to: 'notes#not_commentable'

  get 'about', to: 'pages#about'
  get 'contact', to: 'pages#contact'
  mount ActionCable.server => '/cable'
  get ':id', to: 'courses#show', as: 'course_show'
  

  
 # get ':course/:lecture/notes', to: 'lecture#show', as: 'lecture_notes'
  #get ':course/notes', to: 'notes#index', as: 'course_notes'

  
  
  
  
  
  # resources :notes, except: :index do
  #   member do
  #     get :toggle_status
  #   end
  # end
  #get 'notes', to: 'notes#index', as: 'notes_in_course'
  
  
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  
  

 
end

app/models/education_program.rb
class EducationProgram < ApplicationRecord

    #has_many :courses
    has_many :users
    has_many :course_education_programs
    has_many :courses, through: :course_education_programs
    accepts_nested_attributes_for :courses, 
                                    reject_if: lambda { |attributes| attributes['name'].blank? }

   
    validates_presence_of :title, :academic_degree
    enum academic_degree: { bachelor: 0, master: 1, other: 100}
end

app/controllers/education_programs_controller.rb
class EducationProgramsController < ApplicationController
  before_action :set_education_program, only: [:show, :edit, :update, :destroy]
  access student: [:show],
          instructor: :all

  # GET /education_programs
  # GET /education_programs.json
  def index
    @education_programs = EducationProgram.all
  end

  # GET /education_programs/1
  # GET /education_programs/1.json
  def show
  end

  # GET /education_programs/new
  def new
    @education_program = EducationProgram.new
  end

  # GET /education_programs/1/edit
  def edit
  end

  # POST /education_programs
  # POST /education_programs.json
  def create
    @education_program = EducationProgram.new(education_program_params)

    respond_to do |format|
      if @education_program.save
        format.html { redirect_to @education_program, notice: 'Education program was successfully created.' }
        format.json { render :show, status: :created, location: @education_program }
      else
        format.html { render :new }
        format.json { render json: @education_program.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /education_programs/1
  # PATCH/PUT /education_programs/1.json
  def update
    respond_to do |format|
      if @education_program.update(education_program_params)
        format.html { redirect_to @education_program, notice: 'Education program was successfully updated.' }
        format.json { render :show, status: :ok, location: @education_program }
      else
        format.html { render :edit }
        format.json { render json: @education_program.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /education_programs/1
  # DELETE /education_programs/1.json
  def destroy
    @education_program.destroy
    respond_to do |format|
      format.html { redirect_to education_programs_url, notice: 'Education program was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_education_program
      @education_program = EducationProgram.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def education_program_params
      params.require(:education_program).permit(:title, :academic_degree, course_ids: [], courses_attributes: [:name, :code, :credits, :description])
    end
end

app/helpers/education_programs_helper.rb
module EducationProgramsHelper
end

app/views/education_programs/_form.html.erb
<%= form_with(model: education_program, local: true) do |form| %>
  <% if education_program.errors.any? %>
    <% education_program.errors.full_messages.each do |error| %>
      <%= alert_generator(error) %>
    <% end %>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>
  <div class="field">
    <%= form.label :academic_degree %>
    <%= form.select :academic_degree, EducationProgram.academic_degrees.keys.to_a %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/education_programs/edit.html.erb
<h1>Editing Education Program</h1>

<%= render 'form', education_program: @education_program %>

<%= link_to 'Show', @education_program %> |
<%= link_to 'Back', education_programs_path %>

app/views/education_programs/index.html.erb
<h2>Education Programs</h2>
<%= link_to 'Create a new Education Program', new_education_program_path %>
<hr/>

<div class="row">
<% @education_programs.each do |education_program| %>
    <div class=col-md-12>
        <%= link_to education_program.title, education_program %>
    </div>
    <div class="col-md-12">
        <%= link_to 'Edit', edit_education_program_path(education_program) %> | 
        <%= link_to 'Delete', education_program, method: :delete, data: { confirm: 'Are you sure?' } %>
        <hr>
    </div>

    
<% end %>
</div>
<br>

app/views/education_programs/new.html.erb
<h1>New Education Program</h1>

<%= render 'form', education_program: @education_program %>

<%= link_to 'Back', education_programs_path %>

app/views/education_programs/show.html.erb
<div class="container">
  <h2> <%= @education_program.title %></h2>
  <%= link_to 'Edit', edit_education_program_path(@education_program) %> |
  <%= link_to 'Back', education_programs_path %>
  <hr>
  <p>
    <strong>Academic Degree:</strong>
    <%= @education_program.academic_degree %>
  </p>


  <h3>Courses taught in <%= @education_program.title %>:</h3>
  <% @education_program.courses.each do |c| %>
    <p><%= c.name %></p>
  <% end %>
</div>