config/routes.rb
Rails.application.routes.draw do
  #resources :lectures, only: [:index]
  devise_for :users, path_names: { sign_up: 'register', sign_in: 'login', sign_out: 'log_out' }
  resources :education_programs

  authenticated :user do
    root 'courses#index', as: :authenticated_root
  end

  root to: 'pages#home'

  resources :courses, path: '', except: [:show] do
    put :sort, on: :collection
    resources :notes, shallow: true
    resources :lectures, only: [:index, :show]
  end
  
  get 'notes', to: 'notes#my_notes', as: 'my_notes'
  get 'not_commentable', to: 'notes#not_commentable'

  get 'about', to: 'pages#about'
  get 'contact', to: 'pages#contact'
  mount ActionCable.server => '/cable'
  get ':id', to: 'courses#show', as: 'course_show'
  

  
 # get ':course/:lecture/notes', to: 'lecture#show', as: 'lecture_notes'
  #get ':course/notes', to: 'notes#index', as: 'course_notes'

  
  
  
  
  
  # resources :notes, except: :index do
  #   member do
  #     get :toggle_status
  #   end
  # end
  #get 'notes', to: 'notes#index', as: 'notes_in_course'
  
  
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  
  

 
end

app/models/course.rb
class Course < ApplicationRecord
    validates_presence_of :name, :code, :credits

    extend FriendlyId
    friendly_id :name, use: :slugged

    has_many :notes
    has_many :lectures
    has_many :course_education_programs
    has_many :education_programs, through: :course_education_programs
    has_one_attached :thumbnail
    has_one_attached :main_image
    accepts_nested_attributes_for :education_programs,
                                    allow_destroy: true,
                                    reject_if: lambda { |attributes| attributes['title'].blank? }

    def self.by_position
        order("position ASC")
    end
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
    before_action :set_course, only: [:show, :edit, :update, :destroy]
    after_action :auto_generate_lectures, only: [:create]
    layout "courses"

    access instructor: :all, student: { except: [:destroy, :new, :create, :edit, :update] }

    def index
        @courses = Course.joins(:course_education_programs).where(course_education_programs: {education_program_id: current_user.education_program_id})
    end

    def sort
        params[:order].each do |key, value|
            Course.find(value[:id]).update(position: value[:position])
        end
        render body: nil
    end

    def show
    end

    def new
        @course = Course.new
    end

    # POST /courses
    # POST /courses.json
    def create
        @course = Course.new(course_params)

        respond_to do |format|
            if @course.save
                format.html { redirect_to courses_path, notice: 'A new Course was successfully created.' }
                format.json { render :show, status: :created, location: @course }
            else
                format.html { render :new }
                format.json { render json: @course.errors, status: :unprocessable_entity }
            end
        end
    end

    def edit
    end

    # PATCH/PUT /courses/1
    # PATCH/PUT /courses/1.json
    def update
        respond_to do |format|
            if @course.update(course_params)
                format.html { redirect_to courses_path, notice: 'The course info was successfully updated.' }
                format.json { render :show, status: :ok, location: @course }
            else
                format.html { render :edit }
                format.json { render json: @course.errors, status: :unprocessable_entity }
            end
        end
    end


    # DELETE /notes/1
    # DELETE /notes/1.json
    def destroy
        @course.destroy
        respond_to do |format|
            format.html { redirect_to courses_path, notice: 'The Course was successfully deleted.' }
            format.json { head :no_content }
        end
    end

    private

    def set_course
        @course = Course.friendly.find(params[:id])  
    end

    def course_params
        params.require(:course).permit(
            :name, 
            :code, 
            :credits, 
            :description,
            :thumbnail,
            :main_image,
            :education_program_ids,
            education_programs_attributes: [:title, :_destroy]
        )
    end

    def auto_generate_lectures
        12.times do |lecture|
            Lecture.create!(title: "Lecture #{lecture + 1}", date: ((lecture * 7).days.from_now), course_id: @course.id)
        end
    end

end

app/helpers/courses_helper.rb
module CoursesHelper
    def generate_image(height:, width:)
        "https://placeholdit.co//i/#{width}x#{height}"
    end

    def course_image(image, type)
        if image.attached?
            return image
        elsif type == 'thumbnail'
            generate_image(height: 200, width: 400)
        else
            generate_image(height: 300, width: 600)
        end
    end
end

app/views/courses/_course.html.erb
<div class="col-md-4" data-id="<%= course.id %>">
	<div class="card mb-4 box-shadow">
		<%= image_tag course_image(course.thumbnail, 'thumbnail'), height:200, class: 'card-img' %>
		
		<div class="card-body">
			<p class="card-text"><%= link_to course.name, course_show_path(course) %> | <%= course.code %> </p>
			<div class="d-flex justify-content-between align-items-center">
				<div class="btn-group">
					<%= link_to "Notes", course_notes_path(course.slug), class: "btn btn-sm btn-outline-secondary" %>
					<% if logged_in?(:instructor) %>
						<%= link_to "Edit", edit_course_path(course.id), class: "btn btn-sm btn-outline-secondary" %>
						<%= link_to "Remove", 
									course_path(course.id), 
									class: "btn btn-sm btn-outline-danger text-secondary", 
									method: :delete, data: { confirm: 'Are you sure you want to delete the course?' } %>
					<% end %>
				</div>
				<small class="text-muted"><%= course.credits %> credits</small>
			</div>
		</div>
	</div>
</div>

app/views/courses/_form.html.erb
<%= form_with(model: course, local: true) do |form| %>
  <% if course.errors.any? %>
    <% course.errors.full_messages.each do |error| %>
      <%= alert_generator(error) %>
    <% end %>
  <% end %>
  <div class="row">
    <div class="col-md-6">
      <div class="form-group">
        <%= form.label :name %>
        <%= form.text_field :name, class: "form-control" %>
      </div>
      
      <div class="form-group">
        <%= form.label :code %>
        <%= form.text_field :code, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= form.label :credits %>
        <%= form.text_field :credits, class: "form-control" %>
      </div>
    </div>
    <div class="col-md-6">
      <div class="form-group">
        <label class="btn btn-primary">
          Pick your thumbnail image <%= form.file_field :thumbnail, style: 'display:none' %>
        </label>        
      </div>
      <div class="form-group">
        <label class="btn btn-primary">
          Pick your main image <%= form.file_field :main_image, style: 'display:none' %>
      </label> 
      </div>
    </div>

    <div class="col-md-12">    
      <h2>Add Course To Education Programs</h2>
      <div class="form-group">
        <%= form.collection_select(:education_program_ids, EducationProgram.all, :id, :title) %>
      </div>
    </div>

    <div class="col-md-12">
      <div class="form-group">
        <%= form.label :description %>
        <%= form.text_area :description, class: "form-control", rows: 15 %>
      </div>

      <div class="form-group">
        <%= form.submit "Save Course", class: "btn btn-primary btn-block"%>
      </div>
    </div>
  </div>
<% end %>

app/views/courses/edit.html.erb
<div class="container">
    <h1>Edit Course</h1>

    <%= render 'form', course: @course %>

    <%= link_to 'Back', courses_path %>
</div>

app/views/courses/index.html.erb
<div class="album py-5 bg-light">
    
    <div class="container">
        <h1>Courses</h1>
        <%= link_to  "Create a New Course", new_course_path unless logged_in?(:student) %>
        <div class="row <%= "sortable" if logged_in?(:root_admin) %>">
            <%# The colllection-to-partial mapping actually happens automatically when following the @courses/_course convention. %>
            <%# This explicit call is only for practicing how it's done when naming convention can't be followed for some reason. %>
            <%= render partial: 'course', collection: @courses %>
        </div>
    </div>
</div>

app/views/courses/new.html.erb
<div class="container">
    <h1>Create a new course</h1>

    <%= render 'form', course: @course %>

    <%= link_to 'Back', courses_path %>
</div>

app/views/courses/show.html.erb
<div class="container">
    <div class="row">
        <div class="col-md-7">
            <%= image_tag course_image(@course.main_image, 'main_image'), width: '100%' %>
        </div>
        <div class="col-md-5">
            <h1><%= @course.name %></h1>
            <hr>

            <em><strong>Course Code:</strong> <%= @course.code %></em><br>
            <em><strong>Course Credits:</strong> <%= @course.credits %></em>
            <hr>
            <p><%= @course.description %></p>
            <%= link_to 'To Notes', course_notes_path(@course.slug) %>
        </div>
    </div>
</div>